=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/centralna.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.toomanysecrets.com/centralna"
    targetNamespace="http://www.toomanysecrets.com/centralna">
    <xs:element name="centralna">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="banke">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="banka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv" type="xs:string"/>
                                        <xs:element name="swift" type="xs:string"/>
                                        <xs:element name="stanje" type="xs:decimal"/>
                                        <xs:element name="racun">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:length value="18"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="brojacPoslednjePoslateNotifikacije" type="xs:int"/>
                <xs:element name="brojacPoslednjegPoslatogMTNaloga" type="xs:int"/>
                <xs:element name="brojacPoslednjegPrimljenogMTNaloga">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="banka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv" type="xs:string"/>
                                        <xs:element name="brojac" type="xs:int"/>
                                        <xs:element name="timestamp" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/database/centralna.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:centralna xmlns:ns1="http://www.toomanysecrets.com/centralna"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.toomanysecrets.com/centralna http://localhost:8081/centralna.xsd">
    <banke>
        <banka>
            <naziv>bankaa</naziv>
            <swift>ERSTSR20</swift>
            <stanje>300000.00</stanje>
            <racun>340111111111111111</racun>
        </banka>
        <banka>
            <naziv>bankab</naziv>
            <swift>COMBSR20</swift>
            <stanje>300000.00</stanje>
            <racun>360222222222222222</racun>
        </banka>
    </banke>
    <brojacPoslednjePoslateNotifikacije>0</brojacPoslednjePoslateNotifikacije>
    <brojacPoslednjegPoslatogMTNaloga>0</brojacPoslednjegPoslatogMTNaloga>
    <brojacPoslednjegPrimljenogMTNaloga>
        <banka>
            <naziv>bankaa</naziv>
            <brojac>0</brojac>
            <timestamp>05/04/2006 04:12:55</timestamp>
        </banka>
        <banka>
            <naziv>bankab</naziv>
            <brojac>0</brojac>
            <timestamp>05/04/2006 04:12:55</timestamp>
        </banka>
    </brojacPoslednjegPrimljenogMTNaloga>
</ns1:centralna>
