=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/centralnaSema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.toomanysecrets.com/centralnasema"
    targetNamespace="http://www.toomanysecrets.com/centralnasema">

    <xs:element name="centralnaSema">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="banke">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naziv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="swift">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="stanje">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="racun">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="18"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="brojacPoslednjePoslateNotifikacije" type="xs:int"/>
                <xs:element minOccurs="0" name="brojacPoslednjegPoslatogMTNaloga" type="xs:int"/>
                <xs:element minOccurs="0" name="brojacPoslednjegPrimljenogMTNaloga">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element maxOccurs="1" minOccurs="1" name="banka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nazivBanke">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:maxLength value="255"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="brojac" type="xs:int"/>
                                        <xs:element name="timestamp" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/database/centralnabanka_init.xml
<?xml version="1.0" encoding="UTF-8"?>
<centralnaSema xmlns="http://www.toomanysecrets.com/centralnasema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.toomanysecrets.com/centralnasema file:../shema/centralnaSema.xsd">
    <banke xmlns="">
        <banka>
            <naziv>bankaa</naziv>
            <swift>ERSTSR20</swift>
            <stanje>300000.00</stanje>
            <racun>123456789012345678</racun>
        </banka>
        <banka>
            <naziv>bankab</naziv>
            <swift>BBBBBB00</swift>
            <stanje>300000.00</stanje>
            <racun>444444444444444444</racun>
        </banka>
    </banke>
    <brojacPoslednjePoslateNotifikacije xmlns="">0</brojacPoslednjePoslateNotifikacije>
    <brojacPoslednjegPoslatogMTNaloga xmlns="">0</brojacPoslednjegPoslatogMTNaloga>
    <brojacPoslednjegPrimljenogMTNaloga xmlns="">
        <banka>
            <nazivBanke>bankaa</nazivBanke>
            <brojac>0</brojac>
            <timestamp>05/04/2006 04:12:55</timestamp>
        </banka>
        <banka>
            <nazivBanke>bankab</nazivBanke>
            <brojac>0</brojac>
            <timestamp>05/04/2006 04:12:55</timestamp>
        </banka>
    </brojacPoslednjegPrimljenogMTNaloga>
</centralnaSema>

=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:centralnaSema xmlns:ns1="http://www.toomanysecrets.com/centralnasema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.toomanysecrets.com/centralnasema file:/C:/Users/Milan/Documents/GitHub/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/centralnaSema.xsd">
    <banke>
        <naziv>naziv0</naziv>
        <swift>AAAAAA00</swift>
        <stanje>0.00</stanje>
        <racun>racun1111111111111</racun>
    </banke>
    <banke>
        <naziv>naziv1</naziv>
        <swift>AAAAAA00</swift>
        <stanje>0.00</stanje>
        <racun>racun3333333333333</racun>
    </banke>
    <brojacPoslednjePoslateNotifikacije>0</brojacPoslednjePoslateNotifikacije>
    <brojacPoslednjegPoslatogMTNaloga>0</brojacPoslednjegPoslatogMTNaloga>
    <brojacPoslednjegPrimljenogMTNaloga>
        <banka>
            <nazivBanke>nazivBanke0</nazivBanke>
            <brojac>0</brojac>
            <timestamp>timestamp0</timestamp>
        </banka>
        <banka>
            <nazivBanke>nazivBanke1</nazivBanke>
            <brojac>0</brojac>
            <timestamp>timestamp1</timestamp>
        </banka>
    </brojacPoslednjegPrimljenogMTNaloga>
</ns1:centralnaSema>
