=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/FakturaRaw.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.toomanysecrets.com/faktura"
    xmlns="http://www.toomanysecrets.com/faktura" elementFormDefault="qualified"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0">
    <xs:element name="faktura">


        <xs:complexType>
            <xs:sequence>
                <xs:element name="zaglavlje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nazivDobavljaca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="adresaDobavljaca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pibDobavljaca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="11"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nazivKupca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="55"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="adresaKupca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="55"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pibKupca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="11"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="brojRacuna">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:totalDigits value="6"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="datumRacuna">
                                <xs:simpleType>
                                    <xs:annotation>
                                        <xs:appinfo>
											<jxb:javaType name="java.util.Date" parseMethod="util.MyDatatypeConverter.parseDate" printMethod="util.MyDatatypeConverter.printDate"/>
										</xs:appinfo>
                                    </xs:annotation>
                                    <xs:restriction base="xs:date">
                                        <xs:minInclusive value="1900-01-01"/>
                                        <xs:maxInclusive value="2200-01-01"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="vrednostRobe">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="vrednostUsluga">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ukupnoRobaIUsluge">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ukupanRabat">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ukupanPorez">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="oznakaValute">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="iznosZaUplatu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="uplataNaRacun">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="18"/>
                                        <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                                        <xs:whiteSpace value="preserve"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="datumValute">
                                <xs:simpleType>
                                    <xs:annotation>
                                        <xs:appinfo>
											<jxb:javaType name="java.util.Date" parseMethod="util.MyDatatypeConverter.parseDate" printMethod="util.MyDatatypeConverter.printDate"/>
										</xs:appinfo>
                                    </xs:annotation>
                                    <xs:restriction base="xs:date">
                                        <xs:minInclusive value="1900-01-01"/>
                                        <xs:maxInclusive value="2200-01-01"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idPoruke" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="stavka" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nazivRobeIliUsluge">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="120"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="kolicina">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="10"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="jedinicaMere">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="6"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="jedinicnaCena">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="10"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="vrednost">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="12"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="procenatRabata">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="5"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="iznosRabata">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="12"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="umanjenoZaRabat">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="12"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ukupanPorez">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="12"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="redniBroj" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:totalDigits value="3"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="sender" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luburic/TooManySecrets/ProjekatSaBazom/TestXMLi/TestFaktura3_neispravan_sadrzaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<faktura xmlns="http://www.toomanysecrets.com/faktura" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.toomanysecrets.com/faktura ../WEB-INF/shema/FakturaRaw.xsd ">
  <zaglavlje idPoruke="faktura1">
	<nazivDobavljaca>NIS</nazivDobavljaca>
    <adresaDobavljaca>Bulevar Oslobodjenja 2</adresaDobavljaca>
    <pibDobavljaca>104052135</pibDobavljaca>
    <nazivKupca>DMS</nazivKupca>
    <adresaKupca>Narodnog fronta 3</adresaKupca>
    <pibKupca>105646535</pibKupca>
    <brojRacuna>1</brojRacuna>
    <datumRacuna>2014-01-29</datumRacuna>
    <vrednostRobe>3700.00</vrednostRobe>
    <vrednostUsluga>0.00</vrednostUsluga>
    <ukupnoRobaIUsluge>3700.00</ukupnoRobaIUsluge>
    <ukupanRabat>400.00</ukupanRabat>
    <ukupanPorez>300.00</ukupanPorez>
    <oznakaValute>RSD</oznakaValute>
    <iznosZaUplatu>5000.00</iznosZaUplatu>
    <uplataNaRacun>340111111111111111</uplataNaRacun>
    <datumValute>2014-01-29</datumValute>
  </zaglavlje>
  <stavka redniBroj="1">
    <nazivRobeIliUsluge>Bezolovni</nazivRobeIliUsluge>
    <kolicina>10</kolicina>
    <jedinicaMere>Litra</jedinicaMere>
    <jedinicnaCena>100.00</jedinicnaCena>
    <vrednost>1000.00</vrednost>
    <procenatRabata>10</procenatRabata>
    <iznosRabata>100.0</iznosRabata>
    <umanjenoZaRabat>900.00</umanjenoZaRabat>
    <ukupanPorez>100</ukupanPorez>
  </stavka>
  <stavka redniBroj="2">
    <nazivRobeIliUsluge>Dizel</nazivRobeIliUsluge>
    <kolicina>20</kolicina>
    <jedinicaMere>Litra</jedinicaMere>
    <jedinicnaCena>150.00</jedinicnaCena>
    <vrednost>3000.00</vrednost>
    <procenatRabata>10</procenatRabata>
    <iznosRabata>300.0</iznosRabata>
    <umanjenoZaRabat>2700.00</umanjenoZaRabat>
    <ukupanPorez>200</ukupanPorez>
  </stavka>
</faktura>

=== Luburic/TooManySecrets/ProjekatSaBazom/FakturaTest/faktura-example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<faktura xmlns="http://www.toomanysecrets.com/tipovi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.toomanysecrets.com/tipovi file:/E:/faculty/E2%20cetvrta%20godina/workspace%20kepler/XWSBSEP/WEB-INF/xsdSchemas/FakturaRaw.xsd">
    <zaglavlje idPoruke="idPoruke1">
        <nazivDobavljaca>nazivDobavljaca0</nazivDobavljaca>
        <adresaDobavljaca>adresaDobavljaca0</adresaDobavljaca>
        <pibDobavljaca>22222222222</pibDobavljaca>
        <nazivKupca>nazivKupca0</nazivKupca>
        <adresaKupca>adresaKupca0</adresaKupca>
        <pibKupca>pibKupca0</pibKupca>
        <brojRacuna>0</brojRacuna>
        <datumRacuna>2006-05-04</datumRacuna>
        <vrednostRobe>0.00</vrednostRobe>
        <vrednostUsluga>0.00</vrednostUsluga>
        <ukupnoRobaIUsluge>0.00</ukupnoRobaIUsluge>
        <ukupanRabat>0.00</ukupanRabat>
        <ukupanPorez>0.00</ukupanPorez>
        <oznakaValute>ozn</oznakaValute>
        <iznosZaUplatu>0.00</iznosZaUplatu>
        <uplataNaRacun>000000000000000000</uplataNaRacun>
        <datumValute>2006-05-04</datumValute>
    </zaglavlje>
    <stavka redniBroj="0">
        <nazivRobeIliUsluge>nazivRobeIliUsluge0</nazivRobeIliUsluge>
        <kolicina>0.00</kolicina>
        <jedinicaMere>jedini</jedinicaMere>
        <jedinicnaCena>0.00</jedinicnaCena>
        <vrednost>0.00</vrednost>
        <procenatRabata>0.00</procenatRabata>
        <iznosRabata>0.00</iznosRabata>
        <umanjenoZaRabat>0.00</umanjenoZaRabat>
        <ukupanPorez>0.00</ukupanPorez>
    </stavka>
    <stavka redniBroj="0">
        <nazivRobeIliUsluge>nazivRobeIliUsluge1</nazivRobeIliUsluge>
        <kolicina>0.00</kolicina>
        <jedinicaMere>jedini</jedinicaMere>
        <jedinicnaCena>0.00</jedinicnaCena>
        <vrednost>0.00</vrednost>
        <procenatRabata>0.00</procenatRabata>
        <iznosRabata>0.00</iznosRabata>
        <umanjenoZaRabat>0.00</umanjenoZaRabat>
        <ukupanPorez>0.00</ukupanPorez>
    </stavka>
</faktura>
