=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/registar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.toomanysecrets.com/registar"
    targetNamespace="http://www.toomanysecrets.com/registar">
    <xs:element name="registar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="banke">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="banka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:maxLength value="255"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="swift">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern
                                                  value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"
                                                  />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="adresa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:maxLength value="255"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="racun">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:length value="18"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="code">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:length value="3"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="firme">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="firma">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:maxLength value="255"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="pib">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:maxLength value="11"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="adresa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:maxLength value="255"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="racuni">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                  <xs:element name="racun">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:length value="18"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luburic/TooManySecrets/ProjekatSaBazom/WEB-INF/database/registar_init.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:registar xmlns:ns1="http://www.toomanysecrets.com/registar"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.toomanysecrets.com/registar file:/C:/Users/Milan/Documents/GitHub/TooManySecrets/ProjekatSaBazom/WEB-INF/shema/registar.xsd">
    <banke>
        <banka>
            <naziv>bankaa</naziv>
            <swift>ERSTSR20</swift>
            <adresa>adresa0</adresa>
        </banka>
        <banka>
            <naziv>bankab</naziv>
            <swift>AAAAAA00</swift>
            <adresa>adresa1</adresa>
        </banka>
    </banke>
    <firme>
        <firma>
            <naziv>firmaa</naziv>
            <pib>pib0</pib>
            <adresa>adresa2</adresa>
        </firma>
        <firma>
            <naziv>firmab</naziv>
            <pib>pib1</pib>
            <adresa>adresa3</adresa>
        </firma>
    </firme>
</ns1:registar>
