=== Luburic/TooManySecrets/JBGNoviProjekat/WEB-INF/shema/NalogRaw.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.toomanysecrets.com/tipovi"
    xmlns="http://www.toomanysecrets.com/tipovi" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    jxb:version="2.0">

    <xs:element name="nalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idPoruke">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="duznikNalogodavac">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="svrhaPlacanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="primalacPoverilac">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="255"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="datumNaloga">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:appinfo>
								<jxb:javaType name="java.util.Date" parseMethod="util.MyDatatypeConverter.parseDate" printMethod="util.MyDatatypeConverter.printDate"/>
							</xs:appinfo>
                        </xs:annotation>
                        <xs:restriction base="xs:date">
                            <xs:minInclusive value="1900-01-01"/>
                            <xs:maxInclusive value="2200-01-01"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="datumValute">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:appinfo>
								<jxb:javaType name="java.util.Date" parseMethod="util.MyDatatypeConverter.parseDate" printMethod="util.MyDatatypeConverter.printDate"/>
							</xs:appinfo>
                        </xs:annotation>
                        <xs:restriction base="xs:date">
                            <xs:minInclusive value="1900-01-01"/>
                            <xs:maxInclusive value="2200-01-01"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="racunDuznika">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="18"/>
                            <xs:minLength value="18"/>
                            <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="modelZaduzenja">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:totalDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="pozivNaBrojZaduzenja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="20"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="racunPoverioca">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="18"/>
                            <xs:maxLength value="18"/>
                            <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="modelOdobrenja">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:totalDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="pozivNaBrojOdobrenja">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:totalDigits value="20"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="iznos">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="15"/>
                            <xs:fractionDigits value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="oznakaValute">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="3"/>
                            <xs:minLength value="3"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="hitno" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luburic/TooManySecrets/ProjekatSaBazom/TestXMLi/TestNalog02_ispravan_razlicita_banka_manje_250k.xml
<?xml version="1.0" encoding="UTF-8"?>
<nalog xmlns="http://www.toomanysecrets.com/nalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.toomanysecrets.com/nalog ../WEB-INF/shema/NalogRaw.xsd ">
  <idPoruke>nzpT02</idPoruke>
  <duznikNalogodavac>DMS</duznikNalogodavac>
  <svrhaPlacanja>Placanje fakture fak2</svrhaPlacanja>
  <primalacPoverilac>NIS</primalacPoverilac>
  <datumNaloga>2014-05-25</datumNaloga>
  <datumValute>2014-05-25</datumValute>
  <racunDuznika>310111111111111111</racunDuznika>
  <modelZaduzenja>97</modelZaduzenja>
  <pozivNaBrojZaduzenja>12345678912345678912</pozivNaBrojZaduzenja>
  <racunPoverioca>340111111111111111</racunPoverioca>
  <modelOdobrenja>97</modelOdobrenja>
  <pozivNaBrojOdobrenja>12345678912345678912</pozivNaBrojOdobrenja>
  <iznos>3000.0</iznos>
  <oznakaValute>RSD</oznakaValute>
  <hitno>false</hitno>
</nalog>

=== Luburic/TooManySecrets/JBGNoviProjekat/TestXMLi/nalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<tipovi:nalog xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:tipovi="http://www.toomanysecrets.com/tipovi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.toomanysecrets.com/tipovi file:/C:/Users/Branislav/Desktop/NalogRaw.xsd" idPoruke="idPoruke0">
    <tipovi:duznikNalogodavac>duznikNalogodavac0</tipovi:duznikNalogodavac>
    <tipovi:svrhaPlacanja>svrhaPlacanja0</tipovi:svrhaPlacanja>
    <tipovi:primalacPoverilac>primalacPoverilac0</tipovi:primalacPoverilac>
    <tipovi:datumNaloga>2006-05-04</tipovi:datumNaloga>
    <tipovi:datumValute>2006-05-04</tipovi:datumValute>
    <tipovi:racunDuznika>000000000000000000</tipovi:racunDuznika>
    <tipovi:modelZaduzenja>0</tipovi:modelZaduzenja>
    <tipovi:pozivNaBrojZaduzenja>pozivNaBrojZaduzenja</tipovi:pozivNaBrojZaduzenja>
    <tipovi:racunPoverioca>000000000000000000</tipovi:racunPoverioca>
    <tipovi:modelOdobrenja>0</tipovi:modelOdobrenja>
    <tipovi:pozivNaBrojOdobrenja>0</tipovi:pozivNaBrojOdobrenja>
    <tipovi:iznos>0.00</tipovi:iznos>
    <tipovi:oznakaValute>ozn</tipovi:oznakaValute>
    <tipovi:hitno>false</tipovi:hitno>
</tipovi:nalog>

=== Luburic/TooManySecrets/XWSBSEP/TestXMLi/nalog-example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:nalog idPoruke="" xmlns:p="http://www.toomanysecrets.com/tipovi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.toomanysecrets.com/tipovi ../WEB-INF/shema/NalogRaw.xsd ">
  <p:duznikNalogodavac>BokiÄ‡ DOO</p:duznikNalogodavac>
  <p:svrhaPlacanja>Borko naredio</p:svrhaPlacanja>
  <p:primalacPoverilac>Borko Vukosav</p:primalacPoverilac>
  <p:datumNaloga>2014-01-01</p:datumNaloga>
  <p:datumValute>2014-01-01</p:datumValute>
  <p:racunDuznika>110123456789123455</p:racunDuznika>
  <p:modelZaduzenja>0</p:modelZaduzenja>
  <p:pozivNaBrojZaduzenja>1</p:pozivNaBrojZaduzenja>
  <p:racunPoverioca>220123456789123455</p:racunPoverioca>
  <p:modelOdobrenja>0</p:modelOdobrenja>
  <p:pozivNaBrojOdobrenja>1</p:pozivNaBrojOdobrenja>
  <p:iznos>1000.0</p:iznos>
  <p:oznakaValute>EUR</p:oznakaValute>
  <p:hitno>false</p:hitno>
</p:nalog>

=== Luburic/TooManySecrets/WsImplement/NalogTest/nalog-example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:nalog idPoruke="" xmlns:p="http://www.toomanysecrets.com/tipovi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.toomanysecrets.com/tipovi ../WEB-INF/shema/NalogRaw.xsd ">
  <p:duznikNalogodavac>Bokić DOO</p:duznikNalogodavac>
  <p:svrhaPlacanja>Borko mi je rekao da treba.</p:svrhaPlacanja>
  <p:primalacPoverilac>Univerexport</p:primalacPoverilac>
  <p:datumNaloga>2014-03-05</p:datumNaloga>
  <p:datumValute>2014-03-03</p:datumValute>
  <p:racunDuznika>555123456789123497</p:racunDuznika>
  <p:modelZaduzenja>97</p:modelZaduzenja>
  <p:pozivNaBrojZaduzenja>Poziv na broj zaduženja</p:pozivNaBrojZaduzenja>
  <p:racunPoverioca>444123456789123497</p:racunPoverioca>
  <p:modelOdobrenja>97</p:modelOdobrenja>
  <p:pozivNaBrojOdobrenja>Poziv na broj odobrenja</p:pozivNaBrojOdobrenja>
  <p:iznos>0.0</p:iznos>
  <p:oznakaValute>EUR</p:oznakaValute>
  <p:hitno>false</p:hitno>
</p:nalog>
