=== Luburic/TooManySecrets/wsdl-xsd/shema/MT102Raw.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.toomanysecrets.com/tipovi"
    targetNamespace="http://www.toomanysecrets.com/tipovi" elementFormDefault="qualified">

    <xs:element name="MT102">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zaglavljeMT102">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="swiftBankeDuznika">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="8"/>
                                        <xs:maxLength value="11"/>
                                        <xs:pattern
                                            value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="obracunskiRacunBankeDuzinka">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="18"/>
                                        <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="swiftBankePoverioca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="8"/>
                                        <xs:maxLength value="11"/>
                                        <xs:pattern
                                            value="[A-Z]{4}[A-Z]{2}[0-9A-Z]{2}([0-9A-Z]{3})?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="obracunskiRacunBankePoverioca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="18"/>
                                        <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ukupanIznos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sifraValute">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="datumValute" type="xs:date"/>
                            <xs:element name="datum" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="idPoruke" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="pojedinacnaUplata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="duznik">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="svrhaUplate">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="primalac">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="datumNaloga" type="xs:date"/>
                            <xs:element name="racunDuznika">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="18"/>
                                        <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="modelZaduzenja">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                        <xs:totalDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pozivNaBrojZaduzenja">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="racunPoverioca">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="18"/>
                                        <xs:pattern value="[0-9]{3}[0-9]{13}[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="modelOdobrenja">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                        <xs:totalDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pozivNaBrojOdobrenja">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="iznos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="15"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sifraValute">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idNamogaLzaPlacanje" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Luburic/TooManySecrets/ProjekatSaBazom/TestXMLi/TestClearing4_neispravan_racuni.xml
<?xml version="1.0" encoding="UTF-8"?>
<MT102 xmlns="http://www.toomanysecrets.com/mt102" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.toomanysecrets.com/mt102 ../WEB-INF/shema/MT102Raw.xsd ">
    <zaglavljeMT102 idPoruke="mt102XX9">
        <swiftBankeDuznika>CONARS22</swiftBankeDuznika>
        <obracunskiRacunBankeDuzinka>310000000000000000</obracunskiRacunBankeDuzinka>
        <swiftBankePoverioca>GIBARS22</swiftBankePoverioca>
        <obracunskiRacunBankePoverioca>340000000000000000</obracunskiRacunBankePoverioca>
        <ukupanIznos>2000.00</ukupanIznos>
        <sifraValute>RSD</sifraValute>
        <datumValute>2014-05-25</datumValute>
        <datum>2014-05-25</datum>
    </zaglavljeMT102>
    <pojedinacneUplate>
        <pojedinacnaUplata idNalogaZaPlacanje="nzp1">
            <duznik>DMS</duznik>
            <svrhaUplate>Nafta</svrhaUplate>
            <primalac>NIS</primalac>
            <datumNaloga>2014-05-25</datumNaloga>
            <racunDuznika>310111111111111111</racunDuznika>
            <modelZaduzenja>97</modelZaduzenja>
            <pozivNaBrojZaduzenja>12345678912345678912</pozivNaBrojZaduzenja>
            <racunPoverioca>340111111111111111</racunPoverioca>
            <modelOdobrenja>97</modelOdobrenja>
            <pozivNaBrojOdobrenja>12345678912345678912</pozivNaBrojOdobrenja>
            <iznos>500.00</iznos>
            <sifraValute>RSD</sifraValute>
        </pojedinacnaUplata>
		<pojedinacnaUplata idNalogaZaPlacanje="nzp2">
            <duznik>DMS</duznik>
            <svrhaUplate>Barut</svrhaUplate>
            <primalac>NIS</primalac>
            <datumNaloga>2014-05-25</datumNaloga>
            <racunDuznika>310111111111111111</racunDuznika>
            <modelZaduzenja>97</modelZaduzenja>
            <pozivNaBrojZaduzenja>12345678912345678912</pozivNaBrojZaduzenja>
            <!-- racunPoverioca>340111111111111111</racunPoverioca> -->
            <racunPoverioca>341111111111111111</racunPoverioca>
            <modelOdobrenja>97</modelOdobrenja>
            <pozivNaBrojOdobrenja>12345678912345678912</pozivNaBrojOdobrenja>
            <iznos>1500.00</iznos>
            <sifraValute>RSD</sifraValute>
        </pojedinacnaUplata>
    </pojedinacneUplate>
</MT102>
